using System.Text;
using Newtonsoft.Json;

namespace CsobGatewayClientExample.Communication.DataObjects;

public class Auth3dsSdk : ApiBase
{
 /**
     * Universally unique ID created upon all installations and updates of the
     * 3DS Requestor APp on a Customer Device. This will be newly generated and
     * stored by the 3DS SDK for each installation or update. The field is
     * limited to 36 characters and it shall have a canonical format as defined
     * in IETF RFC 4122. This may utilise any of the specified versions as long
     * as the output meets specified requirements.
     */
 [JsonProperty("appID")]
    public string? AppID { get; set; }

 /**
     * JWE Object as defined Section 6.2.2.1 containing data encrypted by the
     * SDK for the DS to decrypt. This element is the only field encrypted in
     * this version of the EMV 3-D Secure specification. The field is sent from
     * the SDK and it is limited to 64.000 characters. The data will be present
     * when sending to DS, but not present from DS to ACS.
     */
 [JsonProperty("encData")]
    public string? EncData { get; set; }

 /**
     * Public key component of the ephemeral key pair generated by the 3DS SDK
     * and used to establish session keys between the 3DS SDK and ACS. In AReq,
     * this data element is contained within the ACS Signed Content JWS Object.
     * The field is limited to maximum 256 characters.
     */
 [JsonProperty("ephemPubKey")]
    public string? EphemPubKey { get; set; }

 /**
     * Indicates the maximum amount of time (in minutes) for all exchanges. The
     * field shall have value greater or equals than 05.
     */
 [JsonProperty("maxTimeout")]
    public int MaxTimeout { get; set; }

 /**
     * Identifies the vendor and version of the 3DS SDK that is integrated in a
     * 3DS Requestor App, assigned by EMVCo when the 3DS SDK is approved. The
     * field is limited to 32 characters.
     */
 [JsonProperty("referenceNumber")]
    public string? ReferenceNumber { get; set; }

 /**
     * Universally unique transaction identifier assigned by the 3DS SDK to
     * identify a single transaction. The field is limited to 36 characters and
     * it shall be in a canonical format as defined in IETF RFC 4122. This may
     * utilise any of the specified versions as long as the output meets
     * specific requirements.
     */
 [JsonProperty("transID")]
    public string? TransID { get; set; }


    public string ToSign()
    {
        var sb = new StringBuilder();
        Add(sb, AppID);
        Add(sb, EncData);
        Add(sb, EphemPubKey);
        Add(sb, MaxTimeout);
        Add(sb, ReferenceNumber);
        Add(sb, TransID);
        DeleteLast(sb);
        return sb.ToString();
    }
}